Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,6 +5,10 @@ on:
 jobs:
   build:
     name: Build
+    outputs: 
+      project_name: ${{ steps.pom.outputs.name }}
+      sonar_organization: ${{ steps.pom.outputs.organization }}
+      sonar_gate_result: ${{ steps.sonar_analyze_result.outputs.result }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -15,7 +19,6 @@ jobs:
         uses: actions/setup-java@v1
         with:
           java-version: 11
-        
         
       - name: Cache SonarCloud packages
         uses: actions/cache@v1
@@ -30,54 +33,51 @@ jobs:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
+
+      - name: Extract project name in Maven pom.xml file
+        id: pom
+        run: |
+          echo ::set-output name=name::$(grep "<name>" pom.xml | awk -F "name" '{gsub(">|</","",$0); print $2;}')
+          echo ::set-output name=organization::$(grep "<sonar.organization>" pom.xml | awk -F "sonar.organization" '{gsub(">|</","",$0); print $2;}')
+        # echo ::set-output name=name_old::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.name}' --non-recursive exec:exec)          
+      - name: Maven-pom.xml 
+        run: |
+          echo "Project name: ${{ steps.pom.outputs.name }}"
+          echo "Sonar organization: ${{ steps.pom.outputs.organization }}" 
           
-      - name: Build and analyze
+      - name: Build and sonar analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=siberblog_kypnt-devops-backend-release
+        run: |
+          RESULT=$( mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+                      -Dsonar.projectKey=${{ steps.pom.outputs.organization }}_${{ steps.pom.outputs.name }} \
+                      -Dsonar.qualitygate.wait=true \
+                      -Dmaven.test.skip=true \
+                  )
+          echo ::set-output name=result::$( echo $RESULT | grep -o "QUALITY GATE STATUS: PASSED" || echo " Status" ) 
 
 
- 
-      - name: Extract Maven project version
-        id: project
-        run: |
-          echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
-          echo ::set-output name=name::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.name}' --non-recursive exec:exec)
-       
-      - name: Extract short_sha project version
-        id: vars
-        shell: bash
-        run: |
-          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
-        
-      - name: Generate Relase number
-        run: |
-          echo "RELEASE_VERSION=${{ steps.project.outputs.name }}.${{ steps.project.outputs.version }}.${{ steps.vars.outputs.sha_short }}" >> $GITHUB_ENV
-    
-      - name: Create Release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ env.RELEASE_VERSION }}
-          release_name: Release ${{ env.RELEASE_VERSION }}
-          draft: false
-          prerelease: false
-
-  CreateRelease:
-    name: CreateRelease
+  CheckSonarQualityGateResult:
+    name: CheckSonarQualityGateResult
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Get current date
         id: date
-        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
-      - name: Extract Maven project version
-        id: project
         run: |
-          echo "Finish date: ${{ steps.date.outputs.date }}"
-          echo $(date +'%Y-%m-%d')
-          pwd
-          ls -la
+          echo "::set-output name=date::$(date +'%Y-%m-%d')"
+          echo ${{ needs.build.outputs.sonar_gate_result }}
+          
+      - name: Check Quality Gate result and Login Build, Push and Deploy
+        env:
+          COMMIT_VAR: ${{ contains(needs.build.outputs.sonar_gate_result, 'PASSED') }}
+        run: |
+          if ${COMMIT_VAR} == true ; then
+              echo "Evet"
+          else
+              echo "Sonar quality gate is failed."
+              ::exit::failure
+          fi
+          
+
